### ISSUE TITLE
「流畅时钟」未应用时间偏移

### ISSUE THREAD

**Issue by LyCecilion** [LiPolymer/ExtraIsland#1]
![QQ_1731080119498](https://github.com/user-attachments/assets/f25979e3-b4e6-4f81-8bd0-aee9c8006ec0)

「流畅时钟」组件似乎未应用 ClassIsland 中的时间偏移。

**Comment by LiPolymer** [comment]
不好意思 我的疏忽😫

我直接使用了`DateTime.Now`获取系统时间 忘记使用ClassIsland的时间接口

将在下个版本修复 感谢您的提交😊👍

**Comment by LiPolymer** [comment]
该问题已经修复

https://github.com/LiPolymer/ExtraIsland/commit/f6b0a9c8e5a3b0e586700eb9286f8b0a70d33293

再次感谢您的提醒🤗

**Comment by LiPolymer** [comment]
🥳该问题已在 https://github.com/LiPolymer/ExtraIsland/releases/tag/0.0.1.1 修复,请于插件市场更新或前往GitHub/GitLab Release下载手动安装 谢谢您的反馈!

**Comment by LyRin-owo** [comment]
> 不好意思 我的疏忽😫
> 
> 我直接使用了`DateTime.Now`获取系统时间 忘记使用ClassIsland的时间接口
> 
> 😭本人高三牲 学业较为繁忙 未能及时回复请见谅😭
> 
> 将在下个版本修复 感谢您的提交😊👍

😋早期 LiPolymer
