### ISSUE TITLE
FluentClock显示异常

### ISSUE THREAD

**Issue by MOPELotus** [LiPolymer/ExtraIsland#3]
环境：CI 1.5.2.0 测试版本 ExtraIsland仓库版
使用环境：轮播组件下的组合组件下
Bug：轮播到的时候时间为-- 并且动画为前一秒动画卡顿延迟 后一秒动画秒跳 两秒为一个循环
视频链接：http://120.53.241.162/s/Jzysr

**Comment by LiPolymer** [comment]
前述bug已在https://github.com/LiPolymer/ExtraIsland/commit/8642e956efd08f38656191d87533071cf82ef47d 被修复 后一个bug需要迁移动画实现到到'StoryBoard'来提升动画稳定性稳定性

**Comment by LiPolymer** [comment]
🥳 ExtraIsland 已经基本完成`StoryBoard`迁移

通过 https://github.com/LiPolymer/ExtraIsland/commit/01488e4e8f40a93851761747b27386d4472fc1df 和 https://github.com/LiPolymer/ExtraIsland/commit/c58d75815de938e82729cde268d6fb917cccaecd ,本Issue描述的问题应该已经被修复 😋
具体还请下载测试文件*(已发送到ClassIsland QQ群组)*进行测试!
