### ISSUE TITLE
〔bug〕更好的倒计时

### ISSUE THREAD

**Issue by Windows-Edge** [LiPolymer/ExtraIsland#5]
在轮播组件中放3个更好的倒计时，在轮播组件高级设置中启动固定宽度，出现了如图所示的情况
![image](https://github.com/user-attachments/assets/f6744c12-ff3b-4863-9d87-75d24e26f3a7)

**Comment by LiPolymer** [comment]
算了等一月份有空了我再自分配😭

**Comment by LiPolymer** [comment]
🤔初步怀疑为`Grid`控件特性导致
后续将尝试修改为`StackPanel`

**Comment by LiPolymer** [comment]
🥳已在 56ce9f2c 修复
